---
title: "Team Report Census Listing"
author: "Powered by Survey Solutions"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    self_contained: true
    css: style_qManual.css
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
params:
    questionnaireDT: NA
    qTitle: NA
    questions: NA
    team: NA
---


  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NULL, warning = F, message = F)
# source("helpers/source_and_packages.R")
##  For tables
library(kableExtra)
library(knitr)
library(stargazer)
#library(plotly)
library(htmltools)
library(stringr)
library(flextable)
```



```{r plot-dev, include=F, echo=FALSE, eval=TRUE}
dtQ<-params$questionnaireDT
vv<-params$questions
team<-params$team
out<-NULL
for (line in unique(dtQ$ResponsibleName)) {
v<-dtQ[ResponsibleName==line]
env=new.env()
out = c(out, knit_child('plot_child_team.Rmd', quiet=T))
}

```

`r paste(out, collapse = '\n')`






















